apiVersion: v1
kind: Pod
metadata:
  name: owasp-zap-pod
  labels:
    app: owasp-zap
spec:
  containers:
    - name: zap
      image: your-docker-repo/owasp-zap-polling
      ports:
        - containerPort: 8080
      env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: SQS_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/your-account/your-queue.fifo"
        - name: SES_EMAIL_SOURCE
          value: "your-email@example.com"
  restartPolicy: Always
  