apiVersion: v1
kind: Pod
metadata:
  name: owasp-zap-pod
  labels:
    app: owasp-zap
spec:
  containers:
    - name: zap
      image: owasp/zap2docker-stable
      args: [ "zap.sh", "-daemon", "-port", "8080", "-host", "0.0.0.0" ]
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: zap-reports
          mountPath: /zap/reports
      env:
        - name: AWS_REGION
          value: "us-east-2"                 # region here
        - name: SQS_QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/your_account/your-queue.fifo"
        - name: SES_EMAIL_SOURCE
          value: "your-email@example.com"  # AWS SES verified email
  volumes:
    - name: zap-reports
      emptyDir: {}
  restartPolicy: Always
